DROP TABLE WORKOUT_PLANS;
DROP TABLE STAFF;
DROP TABLE WORKSHOPS;
DROP TABLE FITNESS_CLASS;
DROP TABLE PERSONAL_TRAINING_SESSIONS;
DROP TABLE INVOICES;
DROP TABLE PROMOTIONS;
DROP TABLE MEMBERSHIP_PLANS;
DROP TABLE FITNESS_CENTRE;
DROP TABLE MEMBERSHIP;
DROP TABLE PAYMENTS;
DROP TABLE GYM_ATTENDENCE;
DROP TABLE CLIENTS_GUESTS;
DROP TABLE EQUIPMENT_RENTAL;
DROP TABLE HEALTH_ASSESSMENTS;
DROP TABLE MEMBERS;

