--1
SELECT CLASS_NAME,CLASS_TYPE,
(SELECT FIRST_NAME ||' '|| LAST_NAME FROM STAFF WHERE STAFF_ID = FITNESS_CLASSES.INSTRUCTOR_ID) AS INSTRUCTOR_NAME, 
TO_CHAR(SCHEDULE,'DD-MON-YYYY HH24:MI') AS SCHEDULE

FROM FITNESS_CLASSES;

--2
