--1

SELECT CLASS_TYPE AS CLASS_LIST,
(SELECT FIRST_NAME ||' '|| LAST_NAME FROM STAFF WHERE STAFF_ID = FITNESS_CLASSES.INSTRUCTOR_ID) AS INSTRUCTOR_NAME, 
TO_CHAR(SCHEDULE,'DD-MON-YYYY HH24:MI') AS SCHEDULE
FROM FITNESS_CLASSES
ORDER BY CLASS_LIST;

--2

SELECT CLIENTS.FIRST_NAME || ' ' || CLIENTS.LAST_NAME AS CLIENT_NAME, CLASS_BOOKINGS.STATUS
FROM FITNESS_CLASSES
JOIN CLASS_BOOKINGS ON FITNESS_CLASSES.CLASS_ID = CLASS_BOOKINGS.CLASS_ID
JOIN CLIENTS ON CLASS_BOOKINGS.CLIENT_ID = CLIENTS.CLIENT_ID
WHERE FITNESS_CLASSES.CLASS_TYPE = 'Yoga';