-- Add foreign keys to CLIENTS_GUESTS table
ALTER TABLE CLIENTS_GUESTS
ADD CONSTRAINT fk_member_guest
FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID);

-- Add foreign keys to GYM_ATTENDANCE table
ALTER TABLE GYM_ATTENDENCE
ADD CONSTRAINT fk_member_attendance
FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID);

ALTER TABLE GYM_ATTENDENCE
ADD CONSTRAINT fk_guest_attendance
FOREIGN KEY (GUEST_ID) REFERENCES CLIENTS_GUESTS(GUEST_ID);

-- Add foreign keys to PAYMENTS table
ALTER TABLE PAYMENTS
ADD CONSTRAINT fk_member_payments
FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID);

-- Add foreign keys to MEMBERSHIP table
ALTER TABLE MEMBERSHIP
ADD CONSTRAINT fk_plan_membership
FOREIGN KEY (PLAN_ID) REFERENCES MEMBERSHIP_PLANS(PLAN_ID);

-- Add foreign keys to PERSONAL_TRAINING_SESSIONS table
ALTER TABLE PERSONAL_TRAINING_SESSIONS
ADD CONSTRAINT fk_member_training
FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID);

ALTER TABLE PERSONAL_TRAINING_SESSIONS
ADD CONSTRAINT fk_trainer
FOREIGN KEY (TRAINER_ID) REFERENCES STAFF(STAFF_ID);

-- Add foreign keys to FITNESS_CLASS table
ALTER TABLE FITNESS_CLASS
ADD CONSTRAINT fk_centre_class
FOREIGN KEY (CENTRE_ID) REFERENCES FITNESS_CENTRE(CENTRE_ID);

ALTER TABLE FITNESS_CLASS
ADD CONSTRAINT fk_staff_class
FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID);

-- Add foreign keys to WORKSHOPS table
ALTER TABLE WORKSHOPS
ADD CONSTRAINT fk_member_workshop
FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID);

ALTER TABLE WORKSHOPS
ADD CONSTRAINT fk_instructor
FOREIGN KEY (INSTRUCTOR_ID) REFERENCES STAFF(STAFF_ID);

ALTER TABLE WORKSHOPS
ADD CONSTRAINT fk_centre_workshop
FOREIGN KEY (CENTRE_ID) REFERENCES FITNESS_CENTRE(CENTRE_ID);

-- Add foreign keys to WORKOUT_PLANS table
ALTER TABLE WORKOUT_PLANS
ADD CONSTRAINT fk_member_workout
FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID);

ALTER TABLE WORKOUT_PLANS
ADD CONSTRAINT fk_staff_workout
FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID);

ALTER TABLE WORKOUT_PLANS
ADD CONSTRAINT fk_centre_workout
FOREIGN KEY (CENTRE_ID) REFERENCES FITNESS_CENTRE(CENTRE_ID);
